spring:
  # 메세징 관련 설정
  messages:
    basename: messages,errors

# Swagger 설정
springdoc:
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /api/swagger
  cache:
    disabled: true