server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    active: local
    include:
      - secret

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: trace