server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 10MB

  messages:
    basename: messages,errors

  profiles:
    active: local
    include:
      - secret

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: redis
      port: 6379

  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: trace


mail:
  smtp:
    port: 465
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465

springdoc:
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /api/swagger
  cache:
    disabled: true