# Tomcat 웹서버 설정 -> 노출 o + 로컬, 테스트, 운영 환경에 모두 동일한 값으로 필요
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  # 프로필 설정
  profiles:
#    active: local
    include: # 무조건 활성화 하는 프로
      - secret

  # DB 설정 -> 로컬 개발 환경에서 사용
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/gwakkili;
    username: sa
    password:

  # 멀티파트 관련 설정
  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 10MB

  # 메세징 관련 설정
  messages:
    basename: messages,errors

  # JPA 설정 -> 로컬 개발 환경에서 사용
  jpa:
    #defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
#        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false

  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379
      client-type: lettuce

  # Thymeleaf 설정
  thymeleaf:
    cache: false

# 로깅 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: debug


# Swagger 설정
springdoc:
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /api/swagger
  cache:
    disabled: true