name: Java CI with Gradle

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]


permissions:
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "oracle"

      ## gradle build
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean
          ./gradlew bootJar

      ## 도커 이미지 빌드 및 도커 허브 push
      - name: docker image build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }}:backend-latest .
          docker push ${{ secrets.DOCKER_REPO }}:backend-latest

      ## docker compose up
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            docker container rm -f $(docker container ls -qa)
            docker pull ${{ secrets.DOCKER_REPO }}:backend-latest
            docker-compose up -d
            docker image prune -f